[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functionsPort = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
